### ISSUE TITLE
🐺小狼毫输入法配置emoji

### ISSUE THREAD

**Issue by ndon** [ndon/bookmark#1]
``` yaml
# default.custom.yaml  
# save it to:   
#   ~/.config/ibus/rime  (linux)  
#   ~/Library/Rime       (macos)  
#   %APPDATA%\Rime       (windows)  

patch:  
  schema_list:  
    - schema: luna_pinyin_simp     # 朙月拼音 简化字模式  
    - schema: emoji         # emoji表情  
```
